server:
  port: 8080
spring:
  application:
    name: dropBox
    version: 1.0.0
  security:
    oauth2:
      client:
        registration:
          dropbox:
            client-id: API_KEY # Replace with your Client ID
            client-secret: API_SECRET # Replace with your Client Secret
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/api/dropbox/oauth/callback
            scope: team_info.read,members.read,events.read
            client-name: api_integration_for_business_project
        provider:
          dropbox:
            authorization-uri: https://www.dropbox.com/oauth2/authorize
            token-uri: https://api.dropboxapi.com/oauth2/token
            user-info-uri: https://api.dropboxapi.com/2/team/get_info

  datasource:
    url: jdbc:postgresql://localhost:5432/dropBox
    username: postgres
    password: Divya@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  logging:
    level:
      root: INFO
      com.egle.dropbox: DEBUG   # your package
      org.springframework.security: DEBUG
      org.springframework.web.client.RestTemplate: DEBUG



